CREATE TABLE Submissions (
id INT NOT NULL,
lab CHAR(20) NOT NULL,
organism CHAR(40) NULL,
stanza CHAR(40) NULL,
descr CHAR(40) NULL,
tracks VARCHAR(256) NULL,
citation VARCHAR(256) NULL,
gbrowse VARCHAR(256) NULL,
modmine VARCHAR(256) NULL,
machine VARCHAR(256) NULL,
PRIMARY KEY (id)
);


mysql>\u Submissions
mysql>load data local infile 'data_rel***.csv' into table Submissions;

where data_rel***.csv is the file generated by data_filler.pl script
